[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/rashidali/.config/solana/test.json"

[programs.devnet]
gumdrop = "DL4mzu221UJjewGb3KzFt1ifGEBATUtaAsQYGYT3NXDv"

[scripts]
test = "yarn ts-mocha -t 1000000"
